import { describe, expect, it } from 'vitest';

import {
  normalizeSubtitleTranscript,
  normalizeVttTranscript,
  selectSubtitleTrack,
  transcriptLooksUsable,
  type VideoMetadata
} from './transcript';

describe('autoblog transcript helpers', () => {
  it('prefers manual subtitles before automatic captions using configured language priority', () => {
    const metadata: VideoMetadata = {
      id: 'abc123xyz99',
      title: 'OpenAI Agents in Production',
      subtitles: {
        en: [{ ext: 'vtt', url: 'https://example.com/manual-en.vtt' }]
      },
      automatic_captions: {
        'zh-Hans': [{ ext: 'vtt', url: 'https://example.com/auto-zh.vtt' }]
      }
    };

    expect(selectSubtitleTrack(metadata)).toEqual({
      ext: 'vtt',
      isAutoGenerated: false,
      language: 'en',
      url: 'https://example.com/manual-en.vtt'
    });
  });

  it('prefers original automatic captions over translated automatic caption URLs', () => {
    const metadata: VideoMetadata = {
      id: 'abc123xyz99',
      title: 'AI Automation Tutorial',
      automatic_captions: {
        'zh-Hans': [
          {
            ext: 'vtt',
            url: 'https://www.youtube.com/api/timedtext?v=abc123xyz99&lang=en&tlang=zh-Hans&fmt=vtt'
          }
        ],
        en: [
          {
            ext: 'vtt',
            url: 'https://www.youtube.com/api/timedtext?v=abc123xyz99&lang=en&fmt=vtt'
          }
        ]
      }
    };

    expect(selectSubtitleTrack(metadata)).toEqual({
      ext: 'vtt',
      isAutoGenerated: true,
      language: 'en',
      url: 'https://www.youtube.com/api/timedtext?v=abc123xyz99&lang=en&fmt=vtt'
    });
  });

  it('normalizes VTT content into timestamped transcript lines without duplicated text', () => {
    const transcript = normalizeVttTranscript(`WEBVTT

00:00.000 --> 00:03.000
OpenAI agents are useful

00:03.000 --> 00:05.000
OpenAI agents are useful

00:05.000 --> 00:08.000
Ship the workflow with tests
`);

    expect(transcript).toBe('[00:00] OpenAI agents are useful\n[00:05] Ship the workflow with tests');
  });

  it('normalizes json3 subtitles into the same transcript format', () => {
    const transcript = normalizeSubtitleTranscript(
      JSON.stringify({
        events: [
          { tStartMs: 0, segs: [{ utf8: 'OpenAI agents are useful ' }] },
          { tStartMs: 2000, segs: [{ utf8: 'OpenAI agents are useful ' }] },
          { tStartMs: 5000, segs: [{ utf8: 'Ship the workflow with tests' }] }
        ]
      }),
      'json3'
    );

    expect(transcript).toBe('[00:00] OpenAI agents are useful\n[00:05] Ship the workflow with tests');
  });

  it('rejects transcripts that are too short to publish', () => {
    expect(transcriptLooksUsable('too short')).toBe(false);
    expect(transcriptLooksUsable('A'.repeat(900))).toBe(true);
  });
});
