export type SubtitleTrack = {
  ext?: string;
  url: string;
};

export type SubtitleTrackSelection = {
  language: string;
  ext: string;
  url: string;
  isAutoGenerated: boolean;
};

export type VideoMetadata = {
  id: string;
  title: string;
  subtitles?: Record<string, SubtitleTrack[]>;
  automatic_captions?: Record<string, SubtitleTrack[]>;
};

const LANGUAGE_PRIORITY = ['zh-hans', 'zh-cn', 'zh', 'en', 'en-us', 'en-gb'];
const EXTENSION_PRIORITY = ['vtt', 'json3'];

function sortedLanguageEntries(tracks: Record<string, SubtitleTrack[]> | undefined): [string, SubtitleTrack[]][] {
  return Object.entries(tracks ?? {}).sort((a, b) => {
    const aIndex = LANGUAGE_PRIORITY.indexOf(a[0].toLowerCase());
    const bIndex = LANGUAGE_PRIORITY.indexOf(b[0].toLowerCase());
    const normalizedA = aIndex === -1 ? Number.MAX_SAFE_INTEGER : aIndex;
    const normalizedB = bIndex === -1 ? Number.MAX_SAFE_INTEGER : bIndex;

    if (normalizedA !== normalizedB) {
      return normalizedA - normalizedB;
    }

    return a[0].localeCompare(b[0]);
  });
}

function pickTrack(tracks: SubtitleTrack[]): SubtitleTrack | undefined {
  return [...tracks].sort((a, b) => {
    const aIndex = EXTENSION_PRIORITY.indexOf((a.ext ?? '').toLowerCase());
    const bIndex = EXTENSION_PRIORITY.indexOf((b.ext ?? '').toLowerCase());
    const normalizedA = aIndex === -1 ? Number.MAX_SAFE_INTEGER : aIndex;
    const normalizedB = bIndex === -1 ? Number.MAX_SAFE_INTEGER : bIndex;
    return normalizedA - normalizedB;
  })[0];
}

export function selectSubtitleTrack(metadata: VideoMetadata): SubtitleTrackSelection | null {
  for (const [language, tracks] of sortedLanguageEntries(metadata.subtitles)) {
    const selected = pickTrack(tracks);
    if (selected?.url) {
      return {
        language,
        ext: selected.ext ?? 'unknown',
        url: selected.url,
        isAutoGenerated: false
      };
    }
  }

  for (const [language, tracks] of sortedLanguageEntries(metadata.automatic_captions)) {
    const selected = pickTrack(tracks);
    if (selected?.url) {
      return {
        language,
        ext: selected.ext ?? 'unknown',
        url: selected.url,
        isAutoGenerated: true
      };
    }
  }

  return null;
}

function normalizeTimestamp(raw: string): string {
  const parts = raw.replace(',', '.').split(':');
  const [hours = '0', minutes = '00', seconds = '00'] =
    parts.length === 3 ? parts : ['0', parts[0] ?? '00', parts[1] ?? '00'];
  const normalizedHours = Number(hours);
  return normalizedHours > 0
    ? `${String(normalizedHours).padStart(2, '0')}:${minutes}:${seconds.slice(0, 2)}`
    : `${minutes.padStart(2, '0')}:${seconds.slice(0, 2)}`;
}

function formatTimestampFromMilliseconds(milliseconds: number): string {
  const totalSeconds = Math.max(0, Math.floor(milliseconds / 1000));
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  return hours > 0
    ? `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`
    : `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
}

export function normalizeVttTranscript(vtt: string): string {
  const blocks = vtt
    .replace(/^WEBVTT\s*/i, '')
    .split(/\r?\n\r?\n/)
    .map((block) => block.trim())
    .filter(Boolean);

  const lines: string[] = [];
  let previousText = '';

  for (const block of blocks) {
    const parts = block.split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
    const timelineIndex = parts.findIndex((line) => line.includes('-->'));
    if (timelineIndex === -1) {
      continue;
    }

    const timestamp = parts[timelineIndex].split('-->')[0]?.trim();
    const cueText = parts
      .slice(timelineIndex + 1)
      .join(' ')
      .replace(/<[^>]+>/g, '')
      .replace(/&nbsp;/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();

    if (!timestamp || !cueText || cueText === previousText) {
      continue;
    }

    lines.push(`[${normalizeTimestamp(timestamp)}] ${cueText}`);
    previousText = cueText;
  }

  return lines.join('\n');
}

function normalizeJson3Transcript(json: string): string {
  const payload = JSON.parse(json) as {
    events?: Array<{
      tStartMs?: number;
      segs?: Array<{ utf8?: string }>;
    }>;
  };

  const lines: string[] = [];
  let previousText = '';

  for (const event of payload.events ?? []) {
    const cueText = (event.segs ?? [])
      .map((segment) => segment.utf8 ?? '')
      .join(' ')
      .replace(/\s+/g, ' ')
      .trim();

    if (!cueText || cueText === previousText) {
      continue;
    }

    const timestamp = formatTimestampFromMilliseconds(event.tStartMs ?? 0);
    lines.push(`[${timestamp}] ${cueText}`);
    previousText = cueText;
  }

  return lines.join('\n');
}

export function normalizeSubtitleTranscript(raw: string, ext: string): string {
  const normalizedExt = ext.trim().toLowerCase();
  if (normalizedExt === 'json3') {
    return normalizeJson3Transcript(raw);
  }

  return normalizeVttTranscript(raw);
}

export function transcriptLooksUsable(transcript: string, minimumLength = 800): boolean {
  return transcript.trim().length >= minimumLength;
}
